*** 英语连接词

**** 连接词的意义分类

- 表递进 moreover, in addition, what is more，furthermore, also, then, besides, in turn etc.

- 表转折 however, rather than, instead of, but, yet, on the other hand, unfortunately, whereas, while, in fact

- 表让步 although, after all, in spite of..., despite, even if, even though, though, admittedly, whatever may happen.

- 表层次 on the one hand, ... on the other hand; first, ... second, ... finally;

- 表强调 in fact, indeed, actually, as a matter of fact, obviously, apparently,

- 表强调 still, Indeed, apparently, oddly enough, of course, after all, significantly, interestingly, also, above all, surely, certainly, undoubtedly, in any case, anyway, above all, in fact, especially, obviously, clearly.

- 表原因 for this reason, due to, thanks to, because, because of, as, since, owing to, by, out of, when/whenever

- 表结果 evidently, effect, as a result, thus, hence, so, so that, therefore, accordingly, consequently, as consequence

- 表结尾 therefore, as a result, then, consequently, accordingly, thus, etc.

- 下结论 in a word, in conclusion, therefore, in short, to sum up, etc.

- 表比较 like, similarly, likewise, in the same way, in the same manner, equally

- 表对比 by contrast, on the contrary, contradict, while, whereas, on the other hand, unlike, instead, but, conversely, different from, however, nevertheless, otherwise, whereas, unlike, yet, in contrast.

- 表列举 for example, for instance, such as, take ...for example. Except (for), to illustrate.

- 表时间 later, next, then, finally, at last, eventually, meanwhile, from now on, at the same time, for the time being, in the end, immediately, in the meantime, in the meanwhile, recently, soon, now and then, during, nowadays, since, lately, as soon as, afterwards, temporarily, earlier, now, after a while, after a few days,eventually, at that time, in the meantime, meanwhile, afterward, from then on

- 表顺序 first, second, third, then, finally, to begin with, first of all, in the first place, last, next, above all, last but not the least, first and most important.

- 表可能 presumably, probably, perhaps.

- 表解释 be 动词, that is, namely, in simpler terms.

- 表总结 on the whole, in conclusion, in a word, to sum up, in brief, in summary, to conclude, to summarize, in short

**** 常用否定词
- no, not, never, none, nobody, nothing, nowhere, neither, nor, neither...nor, but, without, unless, but for, but that, in the absence of, regardless of, instead of, exclusive of, short of, rather than, anything but, any more than, out of the question, would no more...than

- 由 a-, dis-, il-, im-, ir- ,un-, non-, anti-,mal-,under-等前缀及-less,-free,-proof 等后缀合成的否定词

- hardly, scarcely, barely, little, few, seldom 等半否定词

- avoid, ban, call off, cancel, deny, deprive, exclude, escape, evade, forbid, free...from, free from/of, fail, hate, ignore, lack, lose, miss, naught, neglect, prohibit, quit, refuse, refute , rid, rule out, stop 以及 above, against, beneath, beyond, far from, off, out
